apiVersion: apps/v1
kind: Deployment
metadata:
  name: employees-deployment
  labels:
    app: employees
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employees
      version: v2
  template:
    metadata:
      labels:
        app: employees
        version: v2
        component: frontend
    spec:
      containers:
        - name: employees
          image: 181380864910.dkr.ecr.us-east-1.amazonaws.com/clo835-assignment1-ecr:latest
          imagePullPolicy: Always
          env:
            - name: DBPWD
              valueFrom:
                secretKeyRef:
                  name: mysql-root-password
                  key: MYSQL_ROOT_PASSWORD
            - name: DBPORT
              value: "3306"
            - name: DBHOST
              value: "database-service.sqldb.svc.cluster.local"
            - name: DBUSER
              value: "root"
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 8080

