apiVersion: v1
kind: Pod
metadata:
  name: database-pod
  labels:
    app: mysql
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: backend
spec:
  containers:
    - name: mysql
      image: 181380864910.dkr.ecr.us-east-1.amazonaws.com/clo835-assignment1-ecr:mysql-20240203220702
      imagePullPolicy: Always
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-root-password
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_HOST
          value: localhost
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_DATABASE
          value: employees
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
      ports:
        - containerPort: 3306

