apiVersion: v1
kind: Service
metadata:
  name: database-service
  labels:
    app: mysql
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: backend
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306


