apiVersion: v1
kind: Service
metadata:
  name: aantwi6-service
  labels:
    app: employees
    component: frontend
spec:
  selector:
    app: employees
    component: frontend
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000


